baseURL = 'https://choieastsea.github.io/'
languageCode = 'ko-kr'
title = 'choieastsea.github.io'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "choieastsea"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """글 글 글!"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/user/"


[[params.social]]
name = "github"
url = "https://github.com/user"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "tags"
url = "/tags"


# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = true
repo = "choieastsea/choieastsea.github.io"
repoid = "R_kgDOMgbvhw"
mapping = "pathname"
theme = "preferred_color_scheme"